### ISSUE TITLE
Problema Corrigido ?

### ISSUE THREAD

**Issue by Tindai** [Alexandro-845/CSGO_Elogio_Bot#3]
Em primeiro lugar, peço desculpa se estou publicando no lugar errado, é que não conheço muito a plataforma kkkk..
Então.. O bot ta funcionando normal, pois tentei e não conseguir ?
Se estiver de acordo poderei pagar pelo serviço.

**Comment by AlexandroLuis** [comment]
Atualizei, é pra estar funcionando agr.

**Comment by Tindai** [comment]
Fica dando esse erro. Será que to fazendo algo errado ?

C:\Users\willi\Desktop\CSGO_Elogio_Bot-master\CSGO_Elogio_Bot-master>node index.js
 Update check skipped
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 754 operational accounts
 Parsing target account...
 Chunking 20 accounts into groups of 20...
 Parsing server input
TypeError: Cannot read property 'toUpperCase' of undefined
    at C:\Users\willi\Desktop\CSGO_Elogio_Bot-master\CSGO_Elogio_Bot-master\index.js:276:23 Promise {
  <rejected> TypeError: Cannot read property 'toUpperCase' of undefined
      at C:\Users\willi\Desktop\CSGO_Elogio_Bot-master\CSGO_Elogio_Bot-master\index.js:276:23

**Comment by ghost** [comment]
mesmo erro aqui
ainda

**Comment by Fabricio2006** [comment]
Aqui tmb

**Comment by xsupremepro** [comment]
Mesmo erro aqui ainda também...
