### ISSUE TITLE
Preciso de ajuda?

### ISSUE THREAD

**Issue by Fabricio2006** [Alexandro-845/CSGO_Elogio_Bot#5]
Alexandro pode atualizar pra gente por favor? Tá dando erro ao executar o código logo no npm install ele já apresenta erros, obrigado!

**Comment by xsupremepro** [comment]
Consegui resolver isso, utilizando o comando npm install --force, mas agora estou com outro problema na hora de executar:

TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at C:\csgoelogio\index.js:276:23 Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'toUpperCase')
      at C:\csgoelogio\index.js:276:23
